### ISSUE TITLE
Not working with Python 3.10

### ISSUE THREAD

**Issue by yan12125** [omnilib/aioitertools#84]
### Description
Python 3.10 removes the `loop=` argument from asyncio functions and breaks aioitertools. The issues can be demonstrated by the test suite:
```
$ pyenv install 3.10.0
$ pyenv global 3.10.0
$ ~/.pyenv/shims/python -m venv ~/tmp/venv-3.10
$ source ~/tmp/venv-3.10/bin/activate
$ python -m unittest -v aioitertools.tests
test_as_completed (aioitertools.tests.asyncio.AsyncioTest) ... /home/yen/tmp/aioitertools/aioitertools/tests/helpers.py:13: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
ERROR
test_as_completed_timeout (aioitertools.tests.asyncio.AsyncioTest) ... ERROR
test_gather_cancel (aioitertools.tests.asyncio.AsyncioTest) ... ERROR
test_gather_input_types (aioitertools.tests.asyncio.AsyncioTest) ... ERROR
test_gather_limited (aioitertools.tests.asyncio.AsyncioTest) ... ERROR
test_gather_limited_dupes (aioitertools.tests.asyncio.AsyncioTest) ... ERROR
test_gather_with_exceptions (aioitertools.tests.asyncio.AsyncioTest) ... ERROR
test_import (aioitertools.tests.asyncio.AsyncioTest) ... ok
test_all_async_generator (aioitertools.tests.builtins.BuiltinsTest) ... Task exception was never retrieved
future: <Task finished name='Task-17' coro=<AsyncioTest.test_gather_with_exceptions.<locals>.fn() done, defined at /home/yen/tmp/aioitertools/aioitertools/tests/asyncio.py:115> exception=MyException(0.002)>
Traceback (most recent call last):
  File "/home/yen/tmp/aioitertools/aioitertools/tests/asyncio.py", line 118, in fn
    raise MyException(arg)
aioitertools.tests.asyncio.AsyncioTest.test_gather_with_exceptions.<locals>.MyException: 0.002
ERROR
test_all_generator (aioitertools.tests.builtins.BuiltinsTest) ... ERROR
test_all_list (aioitertools.tests.builtins.BuiltinsTest) ... ERROR
test_all_range (aioitertools.tests.builtins.BuiltinsTest) ... ERROR
test_any_async_generator (aioitertools.tests.builtins.BuiltinsTest) ... ERROR
test_any_generator (aioitertools.tests.builtins.BuiltinsTest) ... ERROR
test_any_list (aioitertools.tests.builtins.BuiltinsTest) ... ERROR
test_any_range (aioitertools.tests.builtins.BuiltinsTest) ... ERROR
test_enumerate (aioitertools.tests.builtins.BuiltinsTest) ... ok
test_enumerate_start (aioitertools.tests.builtins.BuiltinsTest) ... ok
test_iter_async_generator (aioitertools.tests.builtins.BuiltinsTest) ... ok
test_iter_iterable (aioitertools.tests.builtins.BuiltinsTest) ... ok
test_iter_iterator (aioitertools.tests.builtins.BuiltinsTest) ... ok
test_iter_list (aioitertools.tests.builtins.BuiltinsTest) ... ok
test_iter_range (aioitertools.tests.builtins.BuiltinsTest) ... ok
test_list (aioitertools.tests.builtins.BuiltinsTest) ... ok
test_map_coroutine_generator (aioitertools.tests.builtins.BuiltinsTest) ... ok
test_map_coroutine_list (aioitertools.tests.builtins.BuiltinsTest) ... ok
test_map_function_async_generator (aioitertools.tests.builtins.BuiltinsTest) ... ok
test_map_function_list (aioitertools.tests.builtins.BuiltinsTest) ... ok
test_max_basic (aioitertools.tests.builtins.BuiltinsTest) ... ok
test_max_default (aioitertools.tests.builtins.BuiltinsTest) ... ok
test_max_key (aioitertools.tests.builtins.BuiltinsTest) ... ok
test_min_basic (aioitertools.tests.builtins.BuiltinsTest) ... ok
test_min_default (aioitertools.tests.builtins.BuiltinsTest) ... ok
test_min_key (aioitertools.tests.builtins.BuiltinsTest) ... ok
test_next_async_generator (aioitertools.tests.builtins.BuiltinsTest) ... ok
test_next_default_async_iterable (aioitertools.tests.builtins.BuiltinsTest) ... ok
test_next_default_iterable (aioitertools.tests.builtins.BuiltinsTest) ... ok
test_next_iterable (aioitertools.tests.builtins.BuiltinsTest) ... ok
test_next_list (aioitertools.tests.builtins.BuiltinsTest) ... ok
test_next_range (aioitertools.tests.builtins.BuiltinsTest) ... ok
test_set (aioitertools.tests.builtins.BuiltinsTest) ... ok
test_sum_list_string (aioitertools.tests.builtins.BuiltinsTest) ... ok
test_sum_range_default (aioitertools.tests.builtins.BuiltinsTest) ... ok
test_zip_equal (aioitertools.tests.builtins.BuiltinsTest) ... ok
test_maybe_await (aioitertools.tests.helpers.HelpersTest) ... ok
test_maybe_await_async_def (aioitertools.tests.helpers.HelpersTest) ... ok
test_maybe_await_coroutine (aioitertools.tests.helpers.HelpersTest) ... /home/yen/tmp/aioitertools/aioitertools/tests/helpers.py:38: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def forty_two():
ok
test_maybe_await_partial (aioitertools.tests.helpers.HelpersTest) ... ok
test_accumulate_empty (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_accumulate_gen_coroutine (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_accumulate_gen_function (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_accumulate_range_coroutine (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_accumulate_range_default (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_accumulate_range_function (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_chain_from_iterable (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_chain_from_iterable_parameter_expansion_gen (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_chain_list_gens (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_chain_lists (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_combinations (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_combinations_with_replacement (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_compress_gen (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_compress_list (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_count_bare (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_count_negative (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_count_start (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_count_start_step (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_cycle_gen (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_cycle_list (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_dropwhile_coroutine_gen (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_dropwhile_coroutine_list (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_dropwhile_empty (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_dropwhile_function_gen (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_dropwhile_function_list (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_filterfalse_coroutine_list (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_filterfalse_function_list (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_groupby_empty (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_groupby_gen (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_groupby_gen_key (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_groupby_list (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_groupby_list_key (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_islice_bad_range (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_islice_gen_start_step (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_islice_gen_start_stop (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_islice_gen_start_stop_step (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_islice_gen_stop (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_islice_range_start_step (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_islice_range_start_stop (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_islice_range_start_stop_step (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_islice_range_stop (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_islice_stop_zero (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_permutations_gen (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_permutations_list (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_product_gen (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_product_list (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_repeat (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_repeat_limit (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_starmap_coroutine_gen (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_starmap_coroutine_list (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_starmap_function_gen (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_starmap_function_list (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_takewhile_coroutine_gen (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_takewhile_coroutine_list (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_takewhile_empty (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_takewhile_function_gen (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_takewhile_function_list (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_tee_gen_six (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_tee_gen_two (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_tee_list_six (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_tee_list_two (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_tee_propagate_exception (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_zip_longest_exception (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_zip_longest_fillvalue (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_zip_longest_range (aioitertools.tests.itertools.ItertoolsTest) ... ok
test_chunked (aioitertools.tests.more_itertools.MoreItertoolsTest) ... ok
test_chunked_empty (aioitertools.tests.more_itertools.MoreItertoolsTest) ... ok
test_take (aioitertools.tests.more_itertools.MoreItertoolsTest) ... ok
test_take_empty (aioitertools.tests.more_itertools.MoreItertoolsTest) ... ok
test_take_more_than_iterable (aioitertools.tests.more_itertools.MoreItertoolsTest) ... ok
test_take_negative (aioitertools.tests.more_itertools.MoreItertoolsTest) ... ok
test_take_zero (aioitertools.tests.more_itertools.MoreItertoolsTest) ... ok

======================================================================
ERROR: test_as_completed (aioitertools.tests.asyncio.AsyncioTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/tmp/aioitertools/aioitertools/tests/helpers.py", line 14, in wrapped
    return loop.run_until_complete(fn(*args, **kwargs))
  File "/home/yen/.pyenv/versions/3.10.0/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/yen/tmp/aioitertools/aioitertools/tests/asyncio.py", line 29, in test_as_completed
    results = await ait.list(aio.as_completed(futures))
  File "/home/yen/tmp/aioitertools/aioitertools/builtins.py", line 163, in list
    return [item async for item in iter(itr)]
  File "/home/yen/tmp/aioitertools/aioitertools/builtins.py", line 163, in <listcomp>
    return [item async for item in iter(itr)]
  File "/home/yen/tmp/aioitertools/aioitertools/asyncio.py", line 60, in as_completed
    await asyncio.wait(
TypeError: wait() got an unexpected keyword argument 'loop'

======================================================================
ERROR: test_as_completed_timeout (aioitertools.tests.asyncio.AsyncioTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/tmp/aioitertools/aioitertools/tests/helpers.py", line 14, in wrapped
    return loop.run_until_complete(fn(*args, **kwargs))
  File "/home/yen/.pyenv/versions/3.10.0/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/yen/tmp/aioitertools/aioitertools/tests/asyncio.py", line 44, in test_as_completed_timeout
    await ait.list(aio.as_completed(futures, timeout=0.5))
  File "/home/yen/tmp/aioitertools/aioitertools/builtins.py", line 163, in list
    return [item async for item in iter(itr)]
  File "/home/yen/tmp/aioitertools/aioitertools/builtins.py", line 163, in <listcomp>
    return [item async for item in iter(itr)]
  File "/home/yen/tmp/aioitertools/aioitertools/asyncio.py", line 60, in as_completed
    await asyncio.wait(
TypeError: wait() got an unexpected keyword argument 'loop'

======================================================================
ERROR: test_gather_cancel (aioitertools.tests.asyncio.AsyncioTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/tmp/aioitertools/aioitertools/tests/helpers.py", line 14, in wrapped
    return loop.run_until_complete(fn(*args, **kwargs))
  File "/home/yen/.pyenv/versions/3.10.0/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/yen/tmp/aioitertools/aioitertools/tests/asyncio.py", line 157, in test_gather_cancel
    await task
  File "/home/yen/tmp/aioitertools/aioitertools/tests/asyncio.py", line 146, in _gather
    await aio.gather(_fn())
  File "/home/yen/tmp/aioitertools/aioitertools/asyncio.py", line 126, in gather
    done, pending = await asyncio.wait(
TypeError: wait() got an unexpected keyword argument 'loop'

======================================================================
ERROR: test_gather_input_types (aioitertools.tests.asyncio.AsyncioTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/tmp/aioitertools/aioitertools/tests/helpers.py", line 14, in wrapped
    return loop.run_until_complete(fn(*args, **kwargs))
  File "/home/yen/.pyenv/versions/3.10.0/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/yen/tmp/aioitertools/aioitertools/tests/asyncio.py", line 66, in test_gather_input_types
    result = await aio.gather(*fns)
  File "/home/yen/tmp/aioitertools/aioitertools/asyncio.py", line 126, in gather
    done, pending = await asyncio.wait(
TypeError: wait() got an unexpected keyword argument 'loop'

======================================================================
ERROR: test_gather_limited (aioitertools.tests.asyncio.AsyncioTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/tmp/aioitertools/aioitertools/tests/helpers.py", line 14, in wrapped
    return loop.run_until_complete(fn(*args, **kwargs))
  File "/home/yen/.pyenv/versions/3.10.0/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/yen/tmp/aioitertools/aioitertools/tests/asyncio.py", line 83, in test_gather_limited
    result = await aio.gather(*[fn(i) for i in range(10)], limit=2)
  File "/home/yen/tmp/aioitertools/aioitertools/asyncio.py", line 126, in gather
    done, pending = await asyncio.wait(
TypeError: wait() got an unexpected keyword argument 'loop'

======================================================================
ERROR: test_gather_limited_dupes (aioitertools.tests.asyncio.AsyncioTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/tmp/aioitertools/aioitertools/tests/helpers.py", line 14, in wrapped
    return loop.run_until_complete(fn(*args, **kwargs))
  File "/home/yen/.pyenv/versions/3.10.0/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/yen/tmp/aioitertools/aioitertools/tests/asyncio.py", line 102, in test_gather_limited_dupes
    result = await aio.gather(f, f, f, g, f, g, limit=2)
  File "/home/yen/tmp/aioitertools/aioitertools/asyncio.py", line 126, in gather
    done, pending = await asyncio.wait(
TypeError: wait() got an unexpected keyword argument 'loop'

======================================================================
ERROR: test_gather_with_exceptions (aioitertools.tests.asyncio.AsyncioTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/tmp/aioitertools/aioitertools/tests/helpers.py", line 14, in wrapped
    return loop.run_until_complete(fn(*args, **kwargs))
  File "/home/yen/.pyenv/versions/3.10.0/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/yen/tmp/aioitertools/aioitertools/tests/asyncio.py", line 122, in test_gather_with_exceptions
    await aio.gather(fn(0.002, fail=True), fn(0.001))
  File "/home/yen/tmp/aioitertools/aioitertools/asyncio.py", line 126, in gather
    done, pending = await asyncio.wait(
TypeError: wait() got an unexpected keyword argument 'loop'

======================================================================
ERROR: test_all_async_generator (aioitertools.tests.builtins.BuiltinsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/tmp/aioitertools/aioitertools/tests/helpers.py", line 14, in wrapped
    return loop.run_until_complete(fn(*args, **kwargs))
  File "/home/yen/.pyenv/versions/3.10.0/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/yen/tmp/aioitertools/aioitertools/tests/builtins.py", line 38, in test_all_async_generator
    self.assertTrue(await ait.all(ait.iter(srange1)))
  File "/home/yen/tmp/aioitertools/aioitertools/builtins.py", line 69, in all
    return builtins.all(await ait_asyncio.gather_iter(itr))
  File "/home/yen/tmp/aioitertools/aioitertools/asyncio.py", line 163, in gather_iter
    return await gather(
  File "/home/yen/tmp/aioitertools/aioitertools/asyncio.py", line 126, in gather
    done, pending = await asyncio.wait(
TypeError: wait() got an unexpected keyword argument 'loop'

======================================================================
ERROR: test_all_generator (aioitertools.tests.builtins.BuiltinsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/tmp/aioitertools/aioitertools/tests/helpers.py", line 14, in wrapped
    return loop.run_until_complete(fn(*args, **kwargs))
  File "/home/yen/.pyenv/versions/3.10.0/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/yen/tmp/aioitertools/aioitertools/tests/builtins.py", line 33, in test_all_generator
    self.assertTrue(await ait.all(x for x in srange1))
  File "/home/yen/tmp/aioitertools/aioitertools/builtins.py", line 69, in all
    return builtins.all(await ait_asyncio.gather_iter(itr))
  File "/home/yen/tmp/aioitertools/aioitertools/asyncio.py", line 163, in gather_iter
    return await gather(
  File "/home/yen/tmp/aioitertools/aioitertools/asyncio.py", line 126, in gather
    done, pending = await asyncio.wait(
TypeError: wait() got an unexpected keyword argument 'loop'

======================================================================
ERROR: test_all_list (aioitertools.tests.builtins.BuiltinsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/tmp/aioitertools/aioitertools/tests/helpers.py", line 14, in wrapped
    return loop.run_until_complete(fn(*args, **kwargs))
  File "/home/yen/.pyenv/versions/3.10.0/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/yen/tmp/aioitertools/aioitertools/tests/builtins.py", line 23, in test_all_list
    self.assertTrue(await ait.all([True, 1, "string"]))
  File "/home/yen/tmp/aioitertools/aioitertools/builtins.py", line 69, in all
    return builtins.all(await ait_asyncio.gather_iter(itr))
  File "/home/yen/tmp/aioitertools/aioitertools/asyncio.py", line 163, in gather_iter
    return await gather(
  File "/home/yen/tmp/aioitertools/aioitertools/asyncio.py", line 126, in gather
    done, pending = await asyncio.wait(
TypeError: wait() got an unexpected keyword argument 'loop'

======================================================================
ERROR: test_all_range (aioitertools.tests.builtins.BuiltinsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/tmp/aioitertools/aioitertools/tests/helpers.py", line 14, in wrapped
    return loop.run_until_complete(fn(*args, **kwargs))
  File "/home/yen/.pyenv/versions/3.10.0/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/yen/tmp/aioitertools/aioitertools/tests/builtins.py", line 28, in test_all_range
    self.assertTrue(await ait.all(srange1))
  File "/home/yen/tmp/aioitertools/aioitertools/builtins.py", line 69, in all
    return builtins.all(await ait_asyncio.gather_iter(itr))
  File "/home/yen/tmp/aioitertools/aioitertools/asyncio.py", line 163, in gather_iter
    return await gather(
  File "/home/yen/tmp/aioitertools/aioitertools/asyncio.py", line 126, in gather
    done, pending = await asyncio.wait(
TypeError: wait() got an unexpected keyword argument 'loop'

======================================================================
ERROR: test_any_async_generator (aioitertools.tests.builtins.BuiltinsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/tmp/aioitertools/aioitertools/tests/helpers.py", line 14, in wrapped
    return loop.run_until_complete(fn(*args, **kwargs))
  File "/home/yen/.pyenv/versions/3.10.0/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/yen/tmp/aioitertools/aioitertools/tests/builtins.py", line 62, in test_any_async_generator
    self.assertTrue(await ait.any(ait.iter(srange)))
  File "/home/yen/tmp/aioitertools/aioitertools/builtins.py", line 84, in any
    return builtins.any(await ait_asyncio.gather_iter(itr))
  File "/home/yen/tmp/aioitertools/aioitertools/asyncio.py", line 163, in gather_iter
    return await gather(
  File "/home/yen/tmp/aioitertools/aioitertools/asyncio.py", line 126, in gather
    done, pending = await asyncio.wait(
TypeError: wait() got an unexpected keyword argument 'loop'

======================================================================
ERROR: test_any_generator (aioitertools.tests.builtins.BuiltinsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/tmp/aioitertools/aioitertools/tests/helpers.py", line 14, in wrapped
    return loop.run_until_complete(fn(*args, **kwargs))
  File "/home/yen/.pyenv/versions/3.10.0/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/yen/tmp/aioitertools/aioitertools/tests/builtins.py", line 56, in test_any_generator
    self.assertTrue(await ait.any(x for x in srange))
  File "/home/yen/tmp/aioitertools/aioitertools/builtins.py", line 84, in any
    return builtins.any(await ait_asyncio.gather_iter(itr))
  File "/home/yen/tmp/aioitertools/aioitertools/asyncio.py", line 163, in gather_iter
    return await gather(
  File "/home/yen/tmp/aioitertools/aioitertools/asyncio.py", line 126, in gather
    done, pending = await asyncio.wait(
TypeError: wait() got an unexpected keyword argument 'loop'

======================================================================
ERROR: test_any_list (aioitertools.tests.builtins.BuiltinsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/tmp/aioitertools/aioitertools/tests/helpers.py", line 14, in wrapped
    return loop.run_until_complete(fn(*args, **kwargs))
  File "/home/yen/.pyenv/versions/3.10.0/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/yen/tmp/aioitertools/aioitertools/tests/builtins.py", line 45, in test_any_list
    self.assertTrue(await ait.any([False, 1, ""]))
  File "/home/yen/tmp/aioitertools/aioitertools/builtins.py", line 84, in any
    return builtins.any(await ait_asyncio.gather_iter(itr))
  File "/home/yen/tmp/aioitertools/aioitertools/asyncio.py", line 163, in gather_iter
    return await gather(
  File "/home/yen/tmp/aioitertools/aioitertools/asyncio.py", line 126, in gather
    done, pending = await asyncio.wait(
TypeError: wait() got an unexpected keyword argument 'loop'

======================================================================
ERROR: test_any_range (aioitertools.tests.builtins.BuiltinsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/tmp/aioitertools/aioitertools/tests/helpers.py", line 14, in wrapped
    return loop.run_until_complete(fn(*args, **kwargs))
  File "/home/yen/.pyenv/versions/3.10.0/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/yen/tmp/aioitertools/aioitertools/tests/builtins.py", line 50, in test_any_range
    self.assertTrue(await ait.any(srange))
  File "/home/yen/tmp/aioitertools/aioitertools/builtins.py", line 84, in any
    return builtins.any(await ait_asyncio.gather_iter(itr))
  File "/home/yen/tmp/aioitertools/aioitertools/asyncio.py", line 163, in gather_iter
    return await gather(
  File "/home/yen/tmp/aioitertools/aioitertools/asyncio.py", line 126, in gather
    done, pending = await asyncio.wait(
TypeError: wait() got an unexpected keyword argument 'loop'

----------------------------------------------------------------------
Ran 120 tests in 0.035s

FAILED (errors=15)
```

If I also remove `loop=` arguments from aioitertools, tests are green.
```diff
diff --git a/aioitertools/asyncio.py b/aioitertools/asyncio.py
index 663c818..4bc800b 100644
--- a/aioitertools/asyncio.py
+++ b/aioitertools/asyncio.py
@@ -59,7 +59,6 @@ async def as_completed(
             Tuple[Set[Awaitable[T]], Set[Awaitable[T]]],
             await asyncio.wait(
                 pending,
-                loop=loop,
                 timeout=remaining,
                 return_when=asyncio.FIRST_COMPLETED,
             ),
@@ -124,7 +123,7 @@ async def gather(
         if pending:
             try:
                 done, pending = await asyncio.wait(
-                    pending, loop=loop, return_when=asyncio.FIRST_COMPLETED
+                    pending, return_when=asyncio.FIRST_COMPLETED
                 )
                 for x in done:
                     if return_exceptions and x.exception():
@@ -136,7 +135,7 @@ async def gather(
                 for x in pending:
                     x.cancel()
                 # we insure that all tasks are cancelled before we raise
-                await asyncio.gather(*pending, loop=loop, return_exceptions=True)
+                await asyncio.gather(*pending, return_exceptions=True)
                 raise
 
         if not pending and next_arg == len(args):
@@ -162,7 +161,6 @@ async def gather_iter(
     """
     return await gather(
         *[maybe_await(i) async for i in aiter(itr)],
-        loop=loop,
         return_exceptions=return_exceptions,
         limit=limit,
     )
```

I'm not sure if it's a good idea, though, as modified aioitertools functions still accept a `loop=` argument while silently ignores it.

### Details

* OS: Arch Linux
* Python version: 3.10.0 installed from pyenv
* aioitertools version: 0.8.0 and git-master (6594cf4c39318c366d49d97abde75a1b65a1692a)
* Can you repro on master? yes
* Can you repro in a clean virtualenv? yes

**Comment by bnavigator** [comment]
IIUC, it should be safe to remove this parameter. https://stackoverflow.com/questions/60312374/what-are-all-these-deprecated-loop-parameters-in-asyncio
